spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/oasis
    username: root
    password: jkljkl..

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect # dialect도 mariadb에 맞게 설정

  sql:
    init:
      data-locations: classpath:/sql/data.sql # sql 폴더 내에 있는 모든 파일을 실행
      platform: mariadb
      mode: always

