spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/oasis
    username: root
    password: jkljkl..

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true

    show-sql: true

