spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  jwt:
    api:
      secret:
        key: secretKey
    invitation:
      secret:
        key: invTokenSecretKey

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#      spring.jpa.properties.hibernate.format_sql=true
#      spring.jpa.properties.hibernate.show_sql=true
#      spring.jpa.hibernate.ddl-auto=update
#
#      spring.mvc.pathmatch.matching-strategy=ant_path_matcher